name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ajv
        run: npm install -g ajv@7

      - name: Validate PR Configuration
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$')

          if [[ -n $CHANGED_FILES ]]; then
            for FILE in $CHANGED_FILES; do
              if ! jq . $FILE > /dev/null 2>&1; then
                echo "Invalid JSON file: $FILE"
                exit 1
              fi

              if ! ajv test -s schema.json -d $FILE --valid; then
                echo "JSON file does not conform to schema: $FILE"
                exit 1
              fi

              echo "Valid JSON file: $FILE"
            done
          else
            echo "No JSON files found in the commit"
          fi





# name: JSON Validation

# on:
#   push:
#     branches:
#       - main

# jobs:
#   validate-json:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install jq
#         run: sudo apt-get install -y jq

#       - name: Install ajv-cli
#         run: npm install -g ajv-cli

#       - name: Validate JSON files
#         run: |
#           CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$')

#           if [[ -n $CHANGED_FILES ]]; then
#             for FILE in $CHANGED_FILES; do
#               if ! jq . $FILE > /dev/null 2>&1; then
#                 echo "Invalid JSON file: $FILE"
#                 exit 1
#               fi

#               if ! ajv test -s schema.json -d $FILE --valid; then
#                 echo "JSON file does not conform to schema: $FILE"
#                 exit 1
#               fi

#               echo "Valid JSON file: $FILE"
#             done
#           else
#             echo "No JSON files found in the commit"
#           fi
