name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      
      - name: Validate PR Configuration
        run: |
          # Fetch the changed JSON file in the pull request
          CHANGED_FILES=$(git diff --name-only HEAD..$GITHUB_SHA)
          JSON_FILE=""

          # Loop through the changed files to find the JSON file
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == *.json ]]; then
              JSON_FILE=$FILE
              break
            fi
          done

          # If a JSON file is found, validate its format against the schema
          if [[ -n $JSON_FILE ]]; then
            if ! ajv test -s schema.json -d $JSON_FILE --valid; then
              echo "Invalid JSON file: $JSON_FILE"
              exit 1
            else
              echo "Valid JSON file: $JSON_FILE"
            fi
          else
            echo "No JSON file found in the pull request"
          fi
