name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ajv
        run: npm install -g ajv@7
        
      - name: branch list
        run: git branch --list

      - name: Validate PR JSON
        run: |
        
          sudo apt-get update
          sudo apt-get install -y git

          
          PR_FILES=$(git diff --name-only HEAD $(git merge-base HEAD main) -- '*.json')


          if [[ -n $PR_FILES ]]; then
            for FILE in $PR_FILES; do
              if ! jq -e '.github_url' $FILE > /dev/null; then
                echo "The JSON file '$FILE' does not contain the 'github_url' key"
                exit 1
              fi
            done
          else
            echo "No JSON files found in the pull request"
          fi
