name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ajv
        run: npm install -g ajv@7

      - name: Find JSON Files
        run: |
          JSON_FILES=$(git diff --name-only HEAD -- '*.json')
          # Rest of the steps...



          if [[ -n $JSON_FILES ]]; then
            for FILE in $JSON_FILES; do
              if ! jq -e '.github_url' $FILE > /dev/null 2>&1; then
                echo "Invalid JSON file: $FILE - Missing 'github_url' string"

                exit 1
              fi

              echo "Valid JSON file: $FILE"
            done
          else
            echo "No JSON files found in the pull request"
          fi

