name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print changed files
        run: echo "$CHANGED_FILES"



      - name: Install ajv
        run: npm install -g ajv@7

      - name: Validate PR Configuration
        run: |
          # Fetch the changed JSON file in the pull request
          CHANGED_FILES=$(git diff --name-only HEAD..$GITHUB_SHA)
          JSON_FILE=""

          # Loop through the changed files to find the JSON file
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == *.json ]]; then
              JSON_FILE=$FILE
              break
            fi
          done

          # If a JSON file is found, validate its format
          if [[ -n $JSON_FILE ]]; then
            if ! ajv test -s schema.json -d $JSON_FILE --valid; then
              echo "Invalid JSON file: $JSON_FILE"
              exit 1
            else
              echo "Valid JSON file: $JSON_FILE"
            fi
          else
            echo "No JSON file found in the pull request"
          fi
