
name: Check JSON Files in PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Print branch references
        run: |
          echo "Base branch: ${{ env.GITHUB_BASE_REF }}"
          echo "Head branch: ${{ env.GITHUB_HEAD_REF }}"


      - name: Check JSON files
        run: |
          base_commit=$(git merge-base ${{ github.base_ref }} ${{ github.head_ref }})
          git diff --name-only --diff-filter=AM $base_commit ${{ github.head_ref }} | grep '\.json$' | xargs -I {} node -e '
            const fs = require("fs");
            const jsonData = fs.readFileSync(process.cwd() + "/" + "{}", "utf8");
            const jsonObject = JSON.parse(jsonData);
            if (!jsonObject.hasOwnProperty("github_url") || typeof jsonObject.github_url !== "string") {
              console.error(`Error: The file ${process.cwd() + "/" + "{}"} does not have a "github_url" string value.`);
              process.exit(1);
            }
          '











