name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ajv
        run: npm install -g ajv@7

      - name: Validate JSON files
        run: |
          for file in $(git diff --name-only HEAD^ HEAD --diff-filter=d | grep -E '\.json$'); do
            if jq -e 'has("github_url")' "$file" > /dev/null; then
              echo "Valid JSON file: $file"
            else
              echo "Invalid JSON file: $file"
              exit 1
            fi
          done
